# Generated by Django 4.2.30 on 2026-08-09 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='EarningsBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=50)),
                ('business_summary', models.TextField()),
                ('revenue_model', models.TextField()),
                ('key_metrics', models.JSONField(default=dict)),
                ('quarter_vs_prior', models.TextField()),
                ('bull_thesis', models.JSONField(default=dict)),
                ('bear_thesis', models.JSONField(default=dict)),
                ('key_risks', models.JSONField(default=list)),
                ('management_sentiment', models.CharField(max_length=20)),
                ('management_sentiment_evidence', models.TextField()),
                ('red_flags', models.JSONField(default=list)),
                ('analyst_consensus', models.TextField(blank=True, null=True)),
                ('price_targets', models.CharField(blank=True, max_length=255, null=True)),
                ('overall_rating', models.CharField(max_length=20)),
                ('one_line_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='intelligence.ticker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
